### ISSUE TITLE
some problem with train

### ISSUE THREAD

**Issue by rody-ld** [jkulhanek/wild-gaussians#31]
I chose to use “local installation” for installation,when I use : "nerfbaselines train --method wild-gaussians --data external://phototourism/trevi-fountain" to train，The error message is as follows：
info: Using method: wild-gaussians, backend: python
Traceback (most recent call last):
  File "/home/cdh/miniforge3/envs/wildGS/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 499, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 440, in wrapped
    raise e
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 433, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_train.py", line 97, in train_command
    method_cls = stack.enter_context(build_method_class(method_spec, backend_name))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/contextlib.py", line 517, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 89, in build_method_class
    yield cast(Type[Method], backend_impl.static_call(f"{build_method.__module__}:{build_method.__name__}", spec))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/backends/_common.py", line 225, in static_call
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 66, in _build_method_class_internal
    cls: Any = importlib.import_module(package)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wildgaussians'

**Comment by jkulhanek** [comment]
Hi, when following the local install instruction, did you install the wildgaussians package itself by running `pip install -e .` from the root of the cloned repository? From your error, it seems like wild-gaussians itself is not installed.

**Comment by rody-ld** [comment]
Thank you very much! I was careless in the installation. I'm sorry to bother you with this little problem

**Comment by rody-ld** [comment]
Another problem that：I successfully train using: nerfbaselines train --method wild-gaussians --data external://phototourism/trevi-fountain，but when I use: python -m wildgaussians.train --data external://phototourism/trevi-fountain,  error message is as follows：

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/cdh/luodi/wildGS/wildgaussians/train.py", line 380, in <module>
    train_command()  # pylint: disable=no-value-for-parameter
    ^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/miniforge3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/luodi/wildGS/wildgaussians/train.py", line 266, in train_command
    test_dataset = load_dataset_fn(data, "test", features, load_features=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/luodi/wildGS/wildgaussians/datasets/__init__.py", line 60, in load_dataset
    dataset_instance = load_dataset_fn(path, split=split, features=features, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cdh/luodi/wildGS/wildgaussians/datasets/colmap.py", line 236, in load_colmap_dataset
    raise DatasetNotFoundError("Missing 'sparse/0' folder in COLMAP dataset")
wildgaussians.datasets._common.DatasetNotFoundError: Missing 'sparse/0' folder in COLMAP dataset

**Comment by rody-ld** [comment]
I rebuilt the wildgaussians environment on a new platform.When I use: 
python -m wildgaussians.train --data /home/lzj/ld/dataset/trevi-fountain --output output/trevi-fountain
A new problem has arisen:
info: colmap dataloader is loading split data from /home/lzj/ld/dataset/trevi-fountain/test_list.txt
info: loaded dataset from path /home/lzj/ld/dataset/trevi-fountain
info: colmap dataloader is loading split data from /home/lzj/ld/dataset/trevi-fountain/train_list.txt
info: loaded dataset from path /home/lzj/ld/dataset/trevi-fountain
info: Loading images from /home/lzj/ld/dataset/trevi-fountain/images
loading images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1689/1689 [00:07<00:00, 241.12it/s]
info: Loading images from /home/lzj/ld/dataset/trevi-fountain/images
loading images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 225.25it/s]
info: Loading config file default.yml
info: using MLP layer as FFN
Generating skybox: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1689/1689 [00:00<00:00, 6525.32it/s]
info: Adding skybox with 49466 points
Number of points at initialisation :  630139
training:   3%|██                                                                     | 1990/70000 [03:26<1:49:53, 10.32it/s, train/loss=0.1585, psnr=17.0604]info: evaluating on few images at step 2000
                                                                                                                                                             Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]                                                                  | 0/4 [00:00<?, ?it/s]
warning: /home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(

warning: /home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

rendering:   0%|                                                                                                                        | 0/4 [00:00<?, ?it/s]
training:   3%|██                                                                     | 1999/70000 [03:27<1:57:28,  9.65it/s, train/loss=0.1585, psnr=17.0604]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/lzj/ld/wildgs/wildgaussians/train.py", line 380, in <module>
    train_command()  # pylint: disable=no-value-for-parameter
    ^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/train.py", line 343, in train_command
    eval_few_custom(method, logger, train_dataset_eval_few, split="train", step=step, evaluation_protocol=evaluation_protocol)
  File "/home/lzj/ld/wildgs/wildgaussians/train.py", line 165, in eval_few_custom
    metrics.update(compute_metrics(image_to_srgb(result_optim["color"], dtype=np.float32), images_f[i]))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/evaluation.py", line 348, in compute_metrics
    "lpips": reduction(lpips(gt, pred)),
                       ^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/evaluation.py", line 303, in lpips_alex
    return _lpips(a, b, net="alex")
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/evaluation.py", line 266, in _lpips
    lp_net = LPIPS(net=net, version=version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/_metrics_lpips.py", line 114, in __init__
    self.net = net_type(pretrained=not self.pnet_rand, requires_grad=self.pnet_tune)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/ld/wildgs/wildgaussians/_metrics_lpips.py", line 289, in __init__
    alexnet_pretrained_features = tv.alexnet(pretrained=pretrained).features
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/alexnet.py", line 117, in alexnet
    model.load_state_dict(weights.get_state_dict(progress=progress))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torchvision/models/_api.py", line 89, in get_state_dict
    return load_state_dict_from_url(self.url, progress=progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Thank you for helping me out！

**Comment by rody-ld** [comment]
I downloaded the model file directly via the link, and it has been solved. Sorry to bother you

**Comment by rody-ld** [comment]
when I use：nerfbaselines viewer --checkpoint output/trevi-fountain/checkpoint-70000 --data /home/lzj/ld/dataset/trevi-fountain
error message is as follows：
info: Loading checkpoint output/trevi-fountain/checkpoint-70000
info: Using method: wild-gaussians, backend: python
Traceback (most recent call last):
  File "/home/lzj/miniconda3/envs/wildgs/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 499, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 440, in wrapped
    raise e
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 433, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/cli/_viewer.py", line 51, in viewer_command
    method_cls = stack.enter_context(build_method_class(method_spec, backend=backend_name))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/contextlib.py", line 517, in enter_context
    result = _enter(cm)
             ^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 89, in build_method_class
    yield cast(Type[Method], backend_impl.static_call(f"{build_method.__module__}:{build_method.__name__}", spec))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/backends/_common.py", line 225, in static_call
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/site-packages/nerfbaselines/_method_utils.py", line 66, in _build_method_class_internal
    cls: Any = importlib.import_module(package)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzj/miniconda3/envs/wildgs/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wildgaussians.method'

thank you for helping me

**Comment by jkulhanek** [comment]
I assume this is then resolved?
