### ISSUE TITLE
question about train

### ISSUE THREAD

**Issue by whrcn** [jkulhanek/wild-gaussians#32]
Hello author, when I use the command line "nerfbaselines train --method wild-gaussians --data './data/corner'", I have run for 2000 iterations, then it entered an "evaluation phase". Here I encountered network issues, it seems that I need to download the alex.pth weights. I have already downloaded these weights via a URL, but I do not know where they should be placed?
info: Using method: wild-gaussians, backend: python
info: Loading train dataset
info: Loading dataset metadata from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/nb-info.json
warning: Using 'name' field as 'id' field in metadata (nerfbaselines version <1.1.0)
info: Colmap dataloader is loading split data from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/train_list.txt
info: Colmap dataloader is using LLFF split with 101 training images
info: Loaded unknown dataset from path /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner using loader colmap
info: Loading images from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/images
loading images: 100%|███████████████████████| 101/101 [00:00<00:00, 1086.68it/s]
info: Image sizes do not match camera sizes. Resizing cameras to match image sizes.
warning: Downscaled image sizes are not a multiple of camera sizes.
info: Loading eval dataset
info: Loading dataset metadata from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/nb-info.json
warning: Using 'name' field as 'id' field in metadata (nerfbaselines version <1.1.0)
info: Colmap dataloader is loading split data from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/test_list.txt
info: Colmap dataloader is using LLFF split with 101 training images
info: Loaded unknown dataset from path /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner using loader colmap
info: Loading images from /media/hrw/Elements/denoise/cvprmath/wild-gaussians/data/corner/images
loading images: 100%|█████████████████████████| 20/20 [00:00<00:00, 1136.59it/s]
info: Image sizes do not match camera sizes. Resizing cameras to match image sizes.
info: Active presets: nerfonthego
info: Using config overrides: {'config': 'nerfonthego.yml'}
info: Loading config file nerfonthego.yml
info: using MLP layer as FFN
Generating skybox: 100%|████████████████████| 101/101 [00:00<00:00, 4593.73it/s]
info: Adding skybox with 91371 points
Number of points at initialisation :  198767
info: Output directory: /media/hrw/Elements/denoise/cvprmath/wild-gaussians
info: Initialized loggers: tensorboard
training:   7%|▌       | 2000/30000 [01:04<18:41, 24.96it/s, train/psnr=20.2887]info: Rendering single train image at step=2000
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
training:   7%|▌       | 2000/30000 [01:09<16:17, 28.65it/s, train/psnr=20.2887]
Traceback (most recent call last):
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/connectionpool.py", line 713, in urlopen
    self._prepare_proxy(conn)
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1015, in _prepare_proxy
    conn.connect()
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 458, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 502, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /richzhang/PerceptualSimilarity/raw/c33f89e9f46522a584cf41d8880eb0afa982708b/lpips/weights/v0.1/alex.pth (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hrw/anaconda3/envs/wildGS/bin/nerfbaselines", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 499, in invoke
    return super().invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 440, in wrapped
    raise e
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_common.py", line 433, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/cli/_train.py", line 148, in train_command
    trainer.train()
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/training.py", line 792, in train
    self.eval_few()
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/training.py", line 834, in eval_few
    eval_few(self.method, logger, dataset_slice, split="train", step=self.step, evaluation_protocol=self._evaluation_protocol)
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/training.py", line 315, in eval_few
    _metrics = evaluation_protocol.evaluate(predictions, dataset_slice)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/evaluation.py", line 245, in evaluate
    return compute_metrics(pred_f[None], gt_f[None], run_lpips_vgg=self._lpips_vgg, reduce=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/backends/_common.py", line 289, in wrapped
    return Backend.current.static_call(f"{fn.__module__}:{fn.__name__}", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/backends/_common.py", line 225, in static_call
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/evaluation.py", line 115, in compute_metrics
    "lpips": reduction(metrics.lpips(gt, pred)),
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/metrics.py", line 419, in lpips_alex
    return _lpips(a, b, net="alex")
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/metrics.py", line 382, in _lpips
    lp_net = LPIPS(net=net, version=version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/nerfbaselines/_metrics_lpips.py", line 133, in __init__
    response = requests.get(model_url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrw/anaconda3/envs/wildGS/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /richzhang/PerceptualSimilarity/raw/c33f89e9f46522a584cf41d8880eb0afa982708b/lpips/weights/v0.1/alex.pth (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

**Comment by jkulhanek** [comment]
Hi, sorry you are experiencing issues. Can you verify you have internet access from the PC/compute node which runs the code?

**Comment by jkulhanek** [comment]
Newest version of nerfbaselines no longer need Internet access for lpips metrics checkpoints
